add mechanism to specify multiple tests in one file
Add capability to specify more than one test specification within the
same test file.  This allows the tests to share common specifications
but differ where needed.  The driver for this capability is verification
type tests, where you have a long running test and want to have a short
running version without having a completely separate test file.

In a test xml file, add one or more nested <rtest> elements expand the
test file into more than one test.  For example,

  <rtest name="mytest">
    <rtest name="mytest_fast"/>
  </rtest>

All the different test specification elements now allow an attribute
called "testname" that can be used to differentiate the tests in the
same file.  For example,

  <keywords testname="mytest"> long </keywords>
  <keywords testname="mytest_fast"> fast </keywords>

  <parameters testname="mytest" deltah="0.1 0.01 0.001 0.0001"/>
  <parameters testname="mytest_fast" deltah="0.1"/>

  <execute testname="mytest"> do something </execute>

  <analyze testname="mytest"> run analyze script </analyze>

Note that the testname attribute value can be an expression, such as
"not mytest", or "mytest or mytest2".

Small note: the "test_name" attribute of the <link_files> and
<copy_files> elements has been changed to "linkname" instead.  This
is a seldom used specification.

Tests: unit tests PASS

diff --git a/libvvtest/tests/analyze b/libvvtest/tests/analyze
--- a/libvvtest/tests/analyze
+++ b/libvvtest/tests/analyze
@@ -1,269 +1,392 @@
 #!/usr/bin/env python
 
 import os, sys
-import string, re
 import glob
+import time
 
+# this will os.chdir() to a subdirectory
 from testutils import *
 
-rmallfiles()
+def main():
+    """
+    """
+    argL = get_arg_list()
+
+    if len(argL) == 0:
+        argL = """test01 test02 test03 test04 test05 test06 test07
+               """.split()
+
+    savedir = os.getcwd()
+    for func in argL:
+        os.chdir( savedir )
+        rmallfiles()
+        time.sleep(1)
+        print3( '====> ', func )
+        eval( func+'()' )
 
 
 #####################################################################
 
-os.makedirs( 'top/subdir' )
+def test01():
+    """
+    put a parameterize/analyze test at the top level
+    """
+    writefile( 'top/param_analyze.xml', """
+        <rtest name="param_analyze">
+          <keywords> fast medium </keywords>
+          <parameterize keywords="fast"     np="1"/>
+          <parameterize not_keywords="fast" np="2 4"/>
+          <link_files> $NAME.inp </link_files>
+          <execute>
+             touch execute_file.np=$np || exit 1
+             ls $NAME.inp || exit 1
+          </execute>
+          <analyze keywords="fast">
+             ls ../param_analyze.np=1/execute_file.np=1 || exit 1
+          </analyze>
+          <analyze not_keywords="fast">
+             ls ../param_analyze.np=2/execute_file.np=2 || exit 1
+             ls ../param_analyze.np=4/execute_file.np=4 || exit 1
+          </analyze>
+        </rtest>""" )
 
-### put a parameterize/analyze test at the top level
+    writefile( 'top/param_analyze.inp', """
+        some sort of input deck
+        """ )
 
-writefile( 'top/param_analyze.xml', """
-<rtest name="param_analyze">
-  <keywords> fast medium </keywords>
-  <parameterize keywords="fast"     np="1"/>
-  <parameterize not_keywords="fast" np="2 4"/>
-  <link_files> $NAME.inp </link_files>
-  <execute>
-     touch execute_file.np=$np || exit 1
-     ls $NAME.inp || exit 1
-  </execute>
-  <analyze keywords="fast">
-     ls ../param_analyze.np=1/execute_file.np=1 || exit 1
-  </analyze>
-  <analyze not_keywords="fast">
-     ls ../param_analyze.np=2/execute_file.np=2 || exit 1
-     ls ../param_analyze.np=4/execute_file.np=4 || exit 1
-  </analyze>
-</rtest>""" )
+    writefile( 'parentchild/good.xml', """
+        <rtest name="good">
+          <keywords> fast medium </keywords>
+          <parameterize timestep="1 2"/>
+          <execute>
+            touch afile.$timestep
+          </execute>
+          <analyze>
+             ls ../good.timestep=1/afile.1 || exit 1
+             ls ../good.timestep=2/afile.2 || exit 1
+          </analyze>
+        </rtest>""" )
 
-writefile( 'top/param_analyze.inp', """
-some sort of input deck
-""" )
+    writefile( 'parentchild/bad.xml', """
+        <rtest name="bad">
+          <keywords> fast medium </keywords>
+          <parameterize timestep="1 2"/>
+          <execute>
+            echo "fake failure"
+            exit 1
+          </execute>
+          <analyze>
+             ls ../bad.timestep=1/bfile.1 || exit 1
+             ls ../bad.timestep=2/bfile.2 || exit 1
+          </analyze>
+        </rtest>""" )
 
-####################################
+    out,np,nd,nf,nn = run_vvtest( "parentchild" )
+    assert np == 3 and nd == 0 and nf == 2 and nn == 1
 
-os.makedirs( 'parentchild' )
+    # "fix" the bad test
+    writefile( 'parentchild/bad.xml', """
+        <rtest name="bad">
+          <keywords> fast medium </keywords>
+          <parameterize timestep="1 2"/>
+          <execute>
+            touch bfile.$timestep
+          </execute>
+          <analyze>
+             ls ../bad.timestep=1/bfile.1 || exit 1
+             ls ../bad.timestep=2/bfile.2 || exit 1
+          </analyze>
+        </rtest>""" )
 
-writefile( 'parentchild/good.xml', """
-<rtest name="good">
-  <keywords> fast medium </keywords>
-  <parameterize timestep="1 2"/>
-  <execute>
-    touch afile.$timestep
-  </execute>
-  <analyze>
-     ls ../good.timestep=1/afile.1 || exit 1
-     ls ../good.timestep=2/afile.2 || exit 1
-  </analyze>
-</rtest>""" )
-
-writefile( 'parentchild/bad.xml', """
-<rtest name="bad">
-  <keywords> fast medium </keywords>
-  <parameterize timestep="1 2"/>
-  <execute>
-    echo "fake failure"
-    exit 1
-  </execute>
-  <analyze>
-     ls ../bad.timestep=1/bfile.1 || exit 1
-     ls ../bad.timestep=2/bfile.2 || exit 1
-  </analyze>
-</rtest>""" )
-
-out,np,nd,nf,nn = run_vvtest( "parentchild" )
-assert np == 3 and nd == 0 and nf == 2 and nn == 1
-
-# "fix" the bad test
-writefile( 'parentchild/bad.xml', """
-<rtest name="bad">
-  <keywords> fast medium </keywords>
-  <parameterize timestep="1 2"/>
-  <execute>
-    touch bfile.$timestep
-  </execute>
-  <analyze>
-     ls ../bad.timestep=1/bfile.1 || exit 1
-     ls ../bad.timestep=2/bfile.2 || exit 1
-  </analyze>
-</rtest>""" )
-
-out,np,nd,nf,nn = run_vvtest( '-F -k notdone/notrun/fail parentchild' )
-assert np == 3 and nd == 0 and nf == 0 and nn == 0
-
-remove_results()
-
-# exercise logic with only one analyze
-
-writefile( 'parentchild/bad.xml', """
-<rtest name="bad">
-  <keywords> fast medium </keywords>
-  <parameterize timestep="1 2"/>
-  <execute>
-    if ( "$timestep" == 2 ) then
-      echo "fake failure"
-      exit 1
-    else
-      touch bfile.$timestep
-    endif
-  </execute>
-  <analyze>
-     ls ../bad.timestep=1/bfile.1 || exit 1
-     ls ../bad.timestep=2/bfile.2 || exit 1
-  </analyze>
-</rtest>""" )
-
-out,np,nd,nf,nn = run_vvtest( '-k bad parentchild' )
-assert np == 1 and nd == 0 and nf == 1 and nn == 1
-
-# "fix" the bad test
-writefile( 'parentchild/bad.xml', """
-<rtest name="bad">
-  <keywords> fast medium </keywords>
-  <parameterize timestep="1 2"/>
-  <execute>
-    touch bfile.$timestep
-  </execute>
-  <analyze>
-     ls ../bad.timestep=1/bfile.1 || exit 1
-     ls ../bad.timestep=2/bfile.2 || exit 1
-  </analyze>
-</rtest>""" )
-
-out,np,nd,nf,nn = run_vvtest( '-F -k notdone/notrun/fail -k bad parentchild' )
-assert np == 2 and nd == 0 and nf == 0 and nn == 0
-
-platname = platform_name( out )
-print "Extracted platname =", platname
+    out,np,nd,nf,nn = run_vvtest( '-F -k notdone/notrun/fail parentchild' )
+    assert np == 3 and nd == 0 and nf == 0 and nn == 0
 
 
-#########################################
+def test02():
+    """
+    exercise logic with only one analyze
+    """
+    writefile( 'parentchild/good.xml', """
+        <rtest name="good">
+          <keywords> fast medium </keywords>
+          <parameterize timestep="1 2"/>
+          <execute>
+            touch afile.$timestep
+          </execute>
+          <analyze>
+             ls ../good.timestep=1/afile.1 || exit 1
+             ls ../good.timestep=2/afile.2 || exit 1
+          </analyze>
+        </rtest>""" )
+    
+    writefile( 'parentchild/bad.xml', """
+    <rtest name="bad">
+      <keywords> fast medium </keywords>
+      <parameterize timestep="1 2"/>
+      <execute>
+        if ( "$timestep" == 2 ) then
+          echo "fake failure"
+          exit 1
+        else
+          touch bfile.$timestep
+        endif
+      </execute>
+      <analyze>
+         ls ../bad.timestep=1/bfile.1 || exit 1
+         ls ../bad.timestep=2/bfile.2 || exit 1
+      </analyze>
+    </rtest>""" )
 
-remove_results()
+    out,np,nd,nf,nn = run_vvtest( '-k bad parentchild' )
+    assert np == 1 and nd == 0 and nf == 1 and nn == 1
 
-if platname == 'Linux' or platname == 'iDarwin':
-  
-  # same thing but use pipeline
-  
-  writefile( 'parentchild/bad.xml', """
-  <rtest name="bad">
-    <keywords> fast medium </keywords>
-    <parameterize timestep="1 2"/>
-    <execute>
-      echo "fake failure"
-      exit 1
-    </execute>
-    <analyze>
-       ls ../bad.timestep=1/bfile.1 || exit 1
-       ls ../bad.timestep=2/bfile.2 || exit 1
-    </analyze>
-  </rtest>""" )
-  
-  out,np,nd,nf,nn = run_vvtest( '--pipeline parentchild' )
-  assert np == 3 and nd == 0 and nf == 2 and nn == 1
-  
-  # "fix" the bad test
-  writefile( 'parentchild/bad.xml', """
-  <rtest name="bad">
-    <keywords> fast medium </keywords>
-    <parameterize timestep="1 2"/>
-    <execute>
-      touch bfile.$timestep
-    </execute>
-    <analyze>
-       ls ../bad.timestep=1/bfile.1 || exit 1
-       ls ../bad.timestep=2/bfile.2 || exit 1
-    </analyze>
-  </rtest>""" )
-  
-  out,np,nd,nf,nn = run_vvtest( '--pipeline -F -k notdone/notrun/fail parentchild' )
-  assert np == 3 and nd == 0 and nf == 0 and nn == 0
-  
-  remove_results()
-  
-  # exercise logic with only one analyze
-  
-  writefile( 'parentchild/bad.xml', """
-  <rtest name="bad">
-    <keywords> fast medium </keywords>
-    <parameterize timestep="1 2"/>
-    <execute>
-      if ( "$timestep" == 2 ) then
-        echo "fake failure"
-        exit 1
-      else
+    # "fix" the bad test
+    writefile( 'parentchild/bad.xml', """
+    <rtest name="bad">
+      <keywords> fast medium </keywords>
+      <parameterize timestep="1 2"/>
+      <execute>
         touch bfile.$timestep
-      endif
-    </execute>
-    <analyze>
-       ls ../bad.timestep=1/bfile.1 || exit 1
-       ls ../bad.timestep=2/bfile.2 || exit 1
-    </analyze>
-  </rtest>""" )
-  
-  out,np,nd,nf,nn = run_vvtest( '--pipeline -k bad parentchild' )
-  assert np == 1 and nd == 0 and nf == 1 and nn == 1
-  
-  # "fix" the bad test
-  writefile( 'parentchild/bad.xml', """
-  <rtest name="bad">
-    <keywords> fast medium </keywords>
-    <parameterize timestep="1 2"/>
-    <execute>
-      touch bfile.$timestep
-    </execute>
-    <analyze>
-       ls ../bad.timestep=1/bfile.1 || exit 1
-       ls ../bad.timestep=2/bfile.2 || exit 1
-    </analyze>
-  </rtest>""" )
-  
-  out,np,nd,nf,nn = run_vvtest( '--pipeline -F -k notdone/notrun/fail -k bad parentchild' )
-  assert np == 2 and nd == 0 and nf == 0 and nn == 0
+      </execute>
+      <analyze>
+         ls ../bad.timestep=1/bfile.1 || exit 1
+         ls ../bad.timestep=2/bfile.2 || exit 1
+      </analyze>
+    </rtest>""" )
+
+    out,np,nd,nf,nn = run_vvtest( '-F -k notdone/notrun/fail -k bad parentchild' )
+    assert np == 2 and nd == 0 and nf == 0 and nn == 0
+    
+
+def test03():
+    """
+    same as test02 but use pipeline
+    """
+    # determine the platform
+    writefile( "null.xml", """
+        <rtest name="null">
+        </rtest>""" )
+    out,np,nd,nf,nn = run_vvtest()
+    platname = platform_name( out )
+    os.remove( 'null.xml' )
+    remove_results()
+    
+    if platname == 'Linux' or platname == 'iDarwin':
+      
+      writefile( 'parentchild/good.xml', """
+          <rtest name="good">
+            <keywords> fast medium </keywords>
+            <parameterize timestep="1 2"/>
+            <execute>
+              touch afile.$timestep
+            </execute>
+            <analyze>
+               ls ../good.timestep=1/afile.1 || exit 1
+               ls ../good.timestep=2/afile.2 || exit 1
+            </analyze>
+          </rtest>""" )
+      
+      writefile( 'parentchild/bad.xml', """
+          <rtest name="bad">
+            <keywords> fast medium </keywords>
+            <parameterize timestep="1 2"/>
+            <execute>
+              echo "fake failure"
+              exit 1
+            </execute>
+            <analyze>
+               ls ../bad.timestep=1/bfile.1 || exit 1
+               ls ../bad.timestep=2/bfile.2 || exit 1
+            </analyze>
+          </rtest>""" )
+      
+      out,np,nd,nf,nn = run_vvtest( '--pipeline parentchild' )
+      assert np == 3 and nd == 0 and nf == 2 and nn == 1
+      
+      # "fix" the bad test
+      writefile( 'parentchild/bad.xml', """
+          <rtest name="bad">
+            <keywords> fast medium </keywords>
+            <parameterize timestep="1 2"/>
+            <execute>
+              touch bfile.$timestep
+            </execute>
+            <analyze>
+               ls ../bad.timestep=1/bfile.1 || exit 1
+               ls ../bad.timestep=2/bfile.2 || exit 1
+            </analyze>
+          </rtest>""" )
+      
+      out,np,nd,nf,nn = run_vvtest( '--pipeline -F -k notdone/notrun/fail parentchild' )
+      assert np == 3 and nd == 0 and nf == 0 and nn == 0
+      
+      remove_results()
+      
+      # exercise logic with only one analyze
+      
+      writefile( 'parentchild/bad.xml', """
+          <rtest name="bad">
+            <keywords> fast medium </keywords>
+            <parameterize timestep="1 2"/>
+            <execute>
+              if ( "$timestep" == 2 ) then
+                echo "fake failure"
+                exit 1
+              else
+                touch bfile.$timestep
+              endif
+            </execute>
+            <analyze>
+               ls ../bad.timestep=1/bfile.1 || exit 1
+               ls ../bad.timestep=2/bfile.2 || exit 1
+            </analyze>
+          </rtest>""" )
+      
+      out,np,nd,nf,nn = run_vvtest( '--pipeline -k bad parentchild' )
+      assert np == 1 and nd == 0 and nf == 1 and nn == 1
+      
+      # "fix" the bad test
+      writefile( 'parentchild/bad.xml', """
+          <rtest name="bad">
+            <keywords> fast medium </keywords>
+            <parameterize timestep="1 2"/>
+            <execute>
+              touch bfile.$timestep
+            </execute>
+            <analyze>
+               ls ../bad.timestep=1/bfile.1 || exit 1
+               ls ../bad.timestep=2/bfile.2 || exit 1
+            </analyze>
+          </rtest>""" )
+      
+      out,np,nd,nf,nn = run_vvtest( '--pipeline -F -k notdone/notrun/fail -k bad parentchild' )
+      assert np == 2 and nd == 0 and nf == 0 and nn == 0
 
 
-#####################################################################
+def test04():
+    """
+    check that the keywords in an analyze are included in the test keywords
+    """
+    writefile( 'keyw.xml', """
+        <rtest name="keyw">
+          <keywords> fast medium </keywords>
+          <parameterize np="1 2"/>
+          <analyze not_keywords="full"> echo "is not full" </analyze>
+          <analyze keywords="full"> echo "is full" </analyze>
+        </rtest>""" )
 
-rmallfiles()
+    out,np,nd,nf,nn = run_vvtest()
+    assert np == 3 and nd == 0 and nf == 0 and nn == 0
+    fL = glob.glob( 'TestResults.*/keyw/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'is not full' ) ) >= 1
 
-# check that the keywords in an analyze are included in the test keywords
+    out,np,nd,nf,nn = run_vvtest( '-w -k full' )
+    assert np == 3 and nd == 0 and nf == 0 and nn == 0
+    fL = glob.glob( 'TestResults.*/keyw/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'is full' ) ) >= 1
 
-writefile( 'keyw.xml', """
-<rtest name="keyw">
-  <keywords> fast medium </keywords>
-  <parameterize np="1 2"/>
-  <analyze not_keywords="full"> echo "is not full" </analyze>
-  <analyze keywords="full"> echo "is full" </analyze>
-</rtest>""" )
 
-out,np,nd,nf,nn = run_vvtest()
-assert np == 3 and nd == 0 and nf == 0 and nn == 0
-fL = glob.glob( 'TestResults.*/keyw/execute.log' )
-assert len(fL) == 1
-assert len( filegrep( fL[0], 'is not full' ) ) >= 1
+def test05():
+    """
+    check the case where no parameterize but an analyze is given
+    """
+    writefile( 'noparam.xml', """
+        <rtest name="noparam">
+          <keywords> fast medium </keywords>
+          <execute> echo "exec standard" </execute>
+          <analyze>
+            echo "exec analyze"
+          </analyze>
+        </rtest>""" )
 
-out,np,nd,nf,nn = run_vvtest( '-w -k full' )
-assert np == 3 and nd == 0 and nf == 0 and nn == 0
-fL = glob.glob( 'TestResults.*/keyw/execute.log' )
-assert len(fL) == 1
-assert len( filegrep( fL[0], 'is full' ) ) >= 1
+    out,np,nd,nf,nn = run_vvtest()
+    assert np == 1 and nd == 0 and nf == 0 and nn == 0
+    fL = glob.glob( 'TestResults.*/noparam/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec standard' ) ) >= 1
+    assert len( filegrep( fL[0], 'exec analyze' ) ) >= 1
 
-#####################################################################
 
-rmallfiles()
+def test06():
+    """
+    using testname filter with analyze
+    """
+    writefile( 'multi.xml', """
+        <rtest name="multi">
+          <rtest name="multi2"/>
+          <parameterize param="one two"/>
+          <execute> echo "exec test $NAME param $param" </execute>
+          <analyze testname="multi">
+            echo "analyze test $NAME (multi)"
+          </analyze>
+          <analyze testname="multi2">
+            echo "analyze test $NAME (multi2)"
+          </analyze>
+        </rtest>""" )
 
-# check the case where no parameterize but an analyze is given
+    out,np,nd,nf,nn = run_vvtest()
+    assert np == 6 and nd == 0 and nf == 0 and nn == 0
+    
+    fL = glob.glob( 'TestResults.*/multi.param=one/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi.param=two/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'analyze test multi ' ) ) >= 1
+    
+    fL = glob.glob( 'TestResults.*/multi2.param=one/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi2 ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi2.param=two/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi2 ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi2/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'analyze test multi2 ' ) ) >= 1
 
-writefile( 'noparam.xml', """
-<rtest name="noparam">
-  <keywords> fast medium </keywords>
-  <execute> echo "exec standard" </execute>
-  <analyze>
-    echo "exec analyze"
-  </analyze>
-</rtest>""" )
 
-out,np,nd,nf,nn = run_vvtest()
-assert np == 1 and nd == 0 and nf == 0 and nn == 0
-fL = glob.glob( 'TestResults.*/noparam/execute.log' )
-assert len(fL) == 1
-assert len( filegrep( fL[0], 'exec standard' ) ) >= 1
-assert len( filegrep( fL[0], 'exec analyze' ) ) >= 1
+def test07():
+    """
+    testname filter with analyze where one test does not have an analyze
+    """
+    writefile( 'multi.xml', """
+        <rtest name="multi">
+          <rtest name="multi2"/>
+          <parameterize param="one two"/>
+          <execute> echo "exec test $NAME param $param" </execute>
+          <analyze testname="multi2">
+            echo "analyze test $NAME (multi2)"
+          </analyze>
+        </rtest>""" )
+
+    out,np,nd,nf,nn = run_vvtest()
+    assert np == 5 and nd == 0 and nf == 0 and nn == 0
+    
+    fL = glob.glob( 'TestResults.*/multi.param=one/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi.param=two/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi/execute.log' )
+    assert len(fL) == 0
+    
+    fL = glob.glob( 'TestResults.*/multi2.param=one/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi2 ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi2.param=two/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'exec test multi2 ' ) ) >= 1
+    fL = glob.glob( 'TestResults.*/multi2/execute.log' )
+    assert len(fL) == 1
+    assert len( filegrep( fL[0], 'analyze test multi2 ' ) ) >= 1
+
+
+########################################################################
+
+main()
