Add timeout and baseline support for script tests
Tests: unit tests PASS, add more unit testing

diff --git a/libvvtest/tests/execute b/libvvtest/tests/execute
--- a/libvvtest/tests/execute
+++ b/libvvtest/tests/execute
@@ -570,19 +570,73 @@ def postclean():
         <rtest name="pclean">
             <execute>
                 echo "Elvis has left the building" > afile.txt || exit 1
+                mkdir asubdir || exit 1
+                echo "True that" > asubdir/somefile.txt || exit 1
             </execute>
         </rtest>""" )
+    
+    writescript( 'ana.vvt', """
+        #!/usr/bin/env python
+        #VVT: parameterize : P = 1 2
+        #VVT: analyze : ana.py
+        import os
+        import vvtest_util as vvt
+        print3 = vvt.print3
+        fp = open( 'genfile.txt', 'w' )
+        fp.write( 'param P='+vvt.P+'\\n' )
+        fp.close()
+        """ )
+    writescript( "ana.py", """
+        #!/usr/bin/env python
+        import os
+        import vvtest_util as vvt
+        for P in vvt.PARAM_P:
+            fn = '../'+vvt.NAME+'.P='+P+'/genfile.txt'
+            assert os.path.exists( fn )
+            fp = open( 'anagen.txt', 'a' )
+            fp.write( 'file = '+fn+'\\n' )
+            fp.close()
+        """ )
 
     out,np,nd,nf,nn = run_vvtest()
-    assert np == 1 and nd == 0 and nf == 0 and nn == 0
+    assert np == 4 and nd == 0 and nf == 0 and nn == 0
     tdir = results_dir()
-    fL = glob.glob( tdir+'/pclean/afile.txt' )
-    assert len(fL) == 1
+
+    assert len( glob.glob( tdir+'/pclean/afile.txt' ) ) == 1
+    assert len( glob.glob( tdir+'/pclean/runscript' ) ) == 1
+    assert len( glob.glob( tdir+'/pclean/execute.log' ) ) == 1
+    assert os.path.isdir( tdir+'/pclean/asubdir' )
+    assert len( glob.glob( tdir+'/pclean/asubdir/somefile.txt' ) ) == 1
+    
+    assert len( glob.glob( tdir+'/ana/ana.vvt' ) ) == 1
+    assert len( glob.glob( tdir+'/ana/ana.py' ) ) == 1
+    assert len( glob.glob( tdir+'/ana.P=1/execute.log' ) ) == 1
+    assert len( glob.glob( tdir+'/ana.P=1/ana.py' ) ) == 0
+    assert len( glob.glob( tdir+'/ana.P=2/execute.log' ) ) == 1
+    assert len( glob.glob( tdir+'/ana.P=2/ana.py' ) ) == 0
+    assert len( glob.glob( tdir+'/ana/execute.log' ) ) == 1
+    assert len( glob.glob( tdir+'/ana/anagen.txt' ) ) == 1
 
     out,np,nd,nf,nn = run_vvtest( '-R -C' )
-    assert np == 1 and nd == 0 and nf == 0 and nn == 0
-    fL = glob.glob( tdir+'/pclean/afile.txt' )
-    assert len(fL) == 0
+    assert np == 4 and nd == 0 and nf == 0 and nn == 0
+
+    assert len( glob.glob( tdir+'/pclean/afile.txt' ) ) == 0
+    assert len( glob.glob( tdir+'/pclean/runscript' ) ) == 1
+    assert len( glob.glob( tdir+'/pclean/execute.log' ) ) == 1
+    assert not os.path.exists( tdir+'/pclean/asubdir' )
+    assert not os.path.exists( tdir+'/pclean/asubdir/somefile.txt' )
+    
+    # note that the ana.P=1 & 2 tests still have genfile.txt (which if they
+    # were not, the analyze test would fail); that is, the postclean is not
+    # applied to child tests
+    assert len( glob.glob( tdir+'/ana/ana.vvt' ) ) == 1
+    assert len( glob.glob( tdir+'/ana/ana.py' ) ) == 1
+    assert len( glob.glob( tdir+'/ana.P=1/execute.log' ) ) == 1
+    assert len( glob.glob( tdir+'/ana.P=1/ana.py' ) ) == 0
+    assert len( glob.glob( tdir+'/ana.P=2/execute.log' ) ) == 1
+    assert len( glob.glob( tdir+'/ana.P=2/ana.py' ) ) == 0
+    assert len( glob.glob( tdir+'/ana/execute.log' ) ) == 1
+    assert len( glob.glob( tdir+'/ana/anagen.txt' ) ) == 0
 
 
 ############################################################################
