fix issues with --pipeline and the finished mark
There was a subtle behavior issue with the "finished" date stamp
that is written to the test list file.  In --pipeline mode, it was
not getting written, but a second oversight prevented a failure
to occur when the stamp was not written.  Both of these issues are
now fixed.

Tests: unit tests PASS, another pipeline test added

diff --git a/libvvtest/tests/restart b/libvvtest/tests/restart
--- a/libvvtest/tests/restart
+++ b/libvvtest/tests/restart
@@ -118,6 +118,95 @@ def test02():
     assert len( filegrep( tdir+'/clean/execute.log', 'existing.*generated' ) ) == 1
 
 
+#######################################################################
+
+def test03():
+    """
+    restart with pipeline
+    """
+    writefile( 'atest.xml', """
+        <rtest name="atest">
+          <parameterize timestep="1 2"/>
+          <execute>
+            if ( "$timestep" == 2 ) then
+              echo "fake failure"
+              exit 1
+            else
+              touch atest.$timestep
+            endif
+          </execute>
+          <analyze>
+             ls ../atest.timestep=1/atest.1 || exit 1
+             ls ../atest.timestep=2/atest.2 || exit 1
+          </analyze>
+        </rtest>""" )
+
+    out,np,nd,nf,nn = run_vvtest()
+    assert np == 1 and nd == 0 and nf == 1 and nn == 1
+    tdir = os.path.abspath( results_dir() )
+    platname = platform_name( out )
+
+    # "fix" the test and restart
+    writefile( 'atest.xml', """
+        <rtest name="atest">
+          <parameterize timestep="1 2"/>
+          <execute>
+            touch atest.$timestep
+          </execute>
+          <analyze>
+             ls ../atest.timestep=1/atest.1 || exit 1
+             ls ../atest.timestep=2/atest.2 || exit 1
+          </analyze>
+        </rtest>""" )
+    
+    out,np,nd,nf,nn = run_vvtest( '-k fail/notrun' )
+    assert np == 2 and nd == 0 and nf == 0 and nn == 0
+
+    if platname in batchplatforms:
+
+        # same thing in pipeline mode
+
+        remove_results()
+
+        writefile( 'atest.xml', """
+            <rtest name="atest">
+              <parameterize timestep="1 2"/>
+              <execute>
+                if ( "$timestep" == 2 ) then
+                  echo "fake failure"
+                  exit 1
+                else
+                  touch atest.$timestep
+                endif
+              </execute>
+              <analyze>
+                 ls ../atest.timestep=1/atest.1 || exit 1
+                 ls ../atest.timestep=2/atest.2 || exit 1
+              </analyze>
+            </rtest>""" )
+
+        out,np,nd,nf,nn = run_vvtest( '--pipeline' )
+        assert np == 1 and nd == 0 and nf == 1 and nn == 1
+        tdir = os.path.abspath( results_dir() )
+        platname = platform_name( out )
+
+        # "fix" the test and restart
+        writefile( 'atest.xml', """
+            <rtest name="atest">
+              <parameterize timestep="1 2"/>
+              <execute>
+                touch atest.$timestep
+              </execute>
+              <analyze>
+                 ls ../atest.timestep=1/atest.1 || exit 1
+                 ls ../atest.timestep=2/atest.2 || exit 1
+              </analyze>
+            </rtest>""" )
+        
+        out,np,nd,nf,nn = run_vvtest( '--pipeline -k fail/notrun' )
+        assert np == 2 and nd == 0 and nf == 0 and nn == 0
+
+
 ########################################################################
 
 main()
