big test refactor; py2.5 support dropped
Imports were not working quite right for the script_util stuff with
python 2.5.  A little more rigor in the python used inside the testing
infrastructure caught this problem

diff --git a/vvt/libvvtest/tests/execute b/vvt/libvvtest/tests/execute
--- a/vvt/libvvtest/tests/execute
+++ b/vvt/libvvtest/tests/execute
@@ -30,20 +30,17 @@ class execute_tests( unittest.TestCase ):
             <rtest name="null">
             </rtest>""" )
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tL = util.testlist(out)
-        assert len(tL) == 1
-        p = tL[0][-1]
-        assert os.path.exists(p)
+        vrun = util.runvvtest()
+        vrun.assertCounts( total=1, npass=1 )
+        tL = vrun.grepTestLines( '.*' )
+        assert len(tL) == 1 and os.path.exists( tL[0].split()[-1] )
 
     def test_simple_script_test_file(self):
         ""
         util.writefile( 'helloworld.xml', """
             <rtest name="helloworld">
-              <execute> <![CDATA[
-            ${XMLDIR}/helloworld.csh
-            ]]>
+              <execute>
+                <![CDATA[ ${XMLDIR}/helloworld.csh ]]>
               </execute>
             </rtest>""" )
 
@@ -51,14 +48,11 @@ class execute_tests( unittest.TestCase ):
             #!/bin/csh -f
             echo "hello world"
             exit 0""" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tL = util.testlist(out)
-        assert len(tL) == 1
-        p = tL[0][-1]
-        assert os.path.exists(p)
-        assert len( util.filegrep( p+'/execute.log', "^hello world$" ) ) == 1
+        util.runvvtest().assertCounts( total=1, npass=1 )
+        sL = util.grepfiles( 'hello world', 'TestResults*/helloworld/execute.log' )
+        assert len( sL ) == 1
 
     def test_file_link_and_copy_globbing(self):
         ""
@@ -76,16 +70,15 @@ class execute_tests( unittest.TestCase ):
             <rtest name="glob">
               <link_files> glob?.txt </link_files>
               <copy_files> Aglob.* </copy_files>
-              <execute> <![CDATA[
+              <execute>
                 cat glob1.txt || exit 1
                 cat glob2.txt || exit 1
                 cat Aglob.txt || exit 1
-              ]]> 
               </execute>
             </rtest>""")
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
+        util.runvvtest().assertCounts( total=1, npass=1 )
 
     def test_link_and_copy_files_that_do_not_exist(self):
         ""
@@ -125,26 +118,24 @@ class execute_tests( unittest.TestCase ):
                     end
                 </execute>
             </rtest>""")
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 0 and nd == 0 and nf == 4 and nn == 0
-        fL = glob.glob( 'TestResults.*/*/execute.log' )
-        assert len(fL) == 4
-        for f in fL:
-            assert len( util.filegrep( f, "lsfile " ) ) == 0
+        util.runvvtest().assertCounts( total=4, fail=4 )
+
+        sL = util.grepfiles( 'lsfile ', 'TestResults.*/*/execute.log' )
+        assert len( sL ) == 0
 
         # now make it exist and run through to see if the tests work
 
         util.writefile( "file.txt", """
             this is file.txt
             """)
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest( '-R' )
-        assert np == 4 and nd == 0 and nf == 0 and nn == 0
-        fL = glob.glob( 'TestResults.*/*/execute.log' )
-        assert len(fL) == 4
-        for f in fL:
-            assert len( util.filegrep( f, "lsfile file.txt" ) ) == 1
+        util.runvvtest( '-R' ).assertCounts( total=4, npass=4 )
+
+        sL = util.grepfiles( 'lsfile file.txt', 'TestResults.*/*/execute.log' )
+        assert len( sL ) == 4
 
     def test_link_and_copy_files_that_refer_to_parent_directory(self):
         ""
@@ -158,70 +149,64 @@ class execute_tests( unittest.TestCase ):
                     end
                 </execute>
             </rtest>""")
-        util.writefile( "file.txt", """the text file""" )
-        util.writefile( "files/gfile1.txt", """G text file 1""" )
-        util.writefile( "files/gfileA.txt", """G text file A""" )
+        util.writefile( "file.txt", "the text file" )
+        util.writefile( "files/gfile1.txt", "G text file 1" )
+        util.writefile( "files/gfileA.txt", "G text file A" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest( 'subdir' )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        pL = glob.glob( 'TestResults.*' )
-        assert len(pL) == 1
-        f = os.path.join( pL[0], 'links', 'execute.log' )
-        assert len( util.filegrep( f, "lsfile file.txt" ) ) == 1
-        assert len( util.filegrep( f, "lsfile gfile1.txt" ) ) == 1
-        assert len( util.filegrep( f, "lsfile gfileA.txt" ) ) == 1
-        assert os.path.islink( os.path.join( pL[0], 'links', 'file.txt' ) )
-        assert not os.path.islink( os.path.join( pL[0], 'links', 'gfile1.txt' ) )
-        assert not os.path.islink( os.path.join( pL[0], 'links', 'gfileA.txt' ) )
+        vrun = util.runvvtest( 'subdir' )
+        vrun.assertCounts( total=1, npass=1 )
+
+        assert vrun.countGrepLogs( 'lsfile file.txt' ) == 1
+        assert vrun.countGrepLogs( 'lsfile gfile1.txt' ) == 1
+        assert vrun.countGrepLogs( 'lsfile gfileA.txt' ) == 1
+
+        fL = util.findfiles( 'file.txt', 'TestResults*' )
+        assert len(fL) == 1 and os.path.islink( fL[0] )
+        fL = util.findfiles( 'gfile1.txt', 'TestResults*' )
+        assert len(fL) == 1 and not os.path.islink( fL[0] )
+        fL = util.findfiles( 'gfileA.txt', 'TestResults*' )
+        assert len(fL) == 1 and not os.path.islink( fL[0] )
 
     def test_different_test_exit_statuses(self):
         ""
         util.writefile( "PassTest.xml", """
             <rtest name="PassTest">
-              <execute> <![CDATA[
-            sleep 1
-            echo "Exiting with pass status"
-            ]]>
+              <execute>
+                sleep 1
+                echo "Exiting with pass status"
               </execute>
             </rtest>""")
-
         util.writefile( "FailTest.xml", """
             <rtest name="FailTest">
-              <execute> <![CDATA[
-            sleep 1
-            echo "Exiting with failure status"
-            exit 1
-            ]]>
+              <execute>
+                sleep 1
+                echo "Exiting with failure status"
+                exit 1
               </execute>
             </rtest>""")
-
         util.writefile( "DiffTest.xml", """
             <rtest name="DiffTest">
-              <execute> <![CDATA[
-            sleep 1
-            echo "Exiting with diff status"
-            set have_diff = yes
-            ]]>
+              <execute>
+                sleep 1
+                echo "Exiting with diff status"
+                set have_diff = yes
               </execute>
             </rtest>""")
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 1 and nd == 1 and nf == 1 and nn == 0
+        util.runvvtest().assertCounts( total=3, npass=1, diff=1, fail=1 )
 
         # use -L option (and wipe)
 
-        out,np,nd,nf,nn = util.run_vvtest( "-w -L -n 1" )
-        assert np == 1 and nd == 1 and nf == 1 and nn == 0
-        L = re.findall( "Starting test:", out )
-        assert len(L) == 3, "three tests should have run; got "+str(len(L))
+        vrun = util.runvvtest( '-w -L -n 1' )
+        vrun.assertCounts( total=3, npass=1, diff=1, fail=1 )
+        assert vrun.countGrepLines( 'Exiting with ' ) == 3
 
         # check running within the test results directory
 
-        tdir = util.results_dir()
-        os.chdir(tdir+"/PassTest")
-
-        out,np,nd,nf,nn = util.run_vvtest( "-R" )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
+        os.chdir( vrun.resultsDir()+'/PassTest' )
+        util.runvvtest( '-R' ).assertCounts( total=1, npass=1 )
 
     def test_the_XMLDIR_variable(self):
         ""
@@ -230,90 +215,87 @@ class execute_tests( unittest.TestCase ):
         util.writefile( "xdir.xml", """
             <rtest name="xdir">
               <execute> <![CDATA[
-            set echo
-            cd $XMLDIR || exit 1
-            set xdir = `pwd`
-            cd """+cwd+""" || exit 1
-            set cdir = `pwd`
-            if ( $xdir != $cdir ) then
-              echo "*** XMLDIR not equal to """+cwd+""""
-              exit 1
-            endif
-            ]]>
+                set echo
+                cd $XMLDIR || exit 1
+                set xdir = `pwd`
+                cd """+cwd+""" || exit 1
+                set cdir = `pwd`
+                if ( $xdir != $cdir ) then
+                  echo "*** XMLDIR not equal to """+cwd+""""
+                  exit 1
+                endif
+                ]]>
               </execute>
             </rtest>""")
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-
-        tdir = util.results_dir()
-        util.remove_results()
+        vrun = util.runvvtest()
+        vrun.assertCounts( total=1, npass=1 )
 
         # check using the -M option
 
+        util.remove_results()
+
         os.mkdir( 'mir' )
-        out,np,nd,nf,nn = util.run_vvtest( "-M "+cwd+"/mir" )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
+        time.sleep(1)
+
+        util.runvvtest( '-M '+cwd+'/mir' ).assertCounts( total=1, npass=1 )
 
         # cd into a test and run it
 
-        os.chdir( tdir + '/xdir' )
-        out,np,nd,nf,nn = util.run_vvtest( "-R" )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
+        os.chdir( vrun.resultsDir()+'/xdir' )
+        util.runvvtest( '-R' ).assertCounts( total=1, npass=1 )
 
     def test_generate_options_g_and_G(self):
         ""
         util.writefile( 'helloworld.xml', """
             <rtest name="helloworld">
-              <execute> <![CDATA[
-            ${XMLDIR}/helloworld.csh
-            ]]>
+              <execute>
+                ${XMLDIR}/helloworld.csh
               </execute>
             </rtest>""" )
-
         util.writescript( 'helloworld.csh', """
             #!/bin/csh -f
             echo "hello world"
             exit 0""" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest( "-gG" )
-        tdir = util.results_dir()
-        os.chdir(tdir+'/helloworld')
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tL = util.testlist(out)
-        assert len(tL) == 1
-        assert len( util.filegrep( 'execute.log', "^hello world$" ) ) == 1
+        vrun = util.runvvtest( '-gG' )
+        vrun.assertCounts( total=1, notrun=1 )
+
+        os.chdir( vrun.resultsDir()+'/helloworld' )
+        util.runvvtest().assertCounts( total=1, npass=1 )
+
+        assert len( util.grepfiles( 'hello world', 'execute.log' ) ) == 1
 
     def test_forcing_parameterize_values_on_command_line(self):
         ""
         util.writefile( "param.xml", """
             <rtest name="param">
               <parameterize hello="world mars"/>
-              <execute> <![CDATA[
-            sleep 1
-            echo "parm=$hello"
-            ]]>
+              <execute>
+                sleep 1
+                echo "parm=$hello"
               </execute>
             </rtest>""" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 2 and nd == 0 and nf == 0 and nn == 0
+        util.runvvtest().assertCounts( total=2, npass=2 )
 
         # force a parameter to take on a user defined value
 
-        out,np,nd,nf,nn = util.run_vvtest( "-S hello=jupiter" )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
+        util.runvvtest( '-S hello=jupiter' ).assertCounts( total=1, npass=1 )
 
-        out,np,nd,nf,nn = util.run_vvtest( "-i" )
-        assert np == 3 and nd == 0 and nf == 0 and nn == 0
-        tL = util.testlist(out)
-        nj = 0 ; nm = 0 ; nw = 0
-        for line in tL:
-          if line[-1].find( "hello=jupiter" ) >= 0: nj = nj + 1
-          if line[-1].find( "hello=mars" ) >= 0: nm = nm + 1
-          if line[-1].find( "hello=world" ) >= 0: nw = nw + 1
-        assert nj == 1 and nm == 1 and nw == 1
+        vrun = util.runvvtest( '-i' )
+        vrun.assertCounts( total=3, npass=3 )
+
+        assert vrun.countTestLines( 'hello=jupiter' ) == 1
+        assert vrun.countTestLines( 'hello=mars' ) == 1
+        assert vrun.countTestLines( 'hello=world' ) == 1
+
+        assert vrun.countGrepLogs( 'parm=jupiter' ) == 1
+        assert vrun.countGrepLogs( 'parm=mars' ) == 1
+        assert vrun.countGrepLogs( 'parm=world' ) == 1
 
     def test_that_the_test_specification_file_is_automatically_soft_linked(self):
         ""
@@ -324,7 +306,6 @@ class execute_tests( unittest.TestCase ):
                 ls -l $NAME.xml || exit 1
               </execute>
             </rtest>""" )
-
         util.writefile( "auto2.xml", """
             <rtest name="auto2">
               <link> $NAME.xml </link>
@@ -333,13 +314,12 @@ class execute_tests( unittest.TestCase ):
                 ls -l $NAME.xml || exit 1
               </execute>
             </rtest>""" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 2 and nd == 0 and nf == 0 and nn == 0
-        fL = glob.glob( 'TestResults.*/auto1/auto1.xml' )
-        assert len(fL) == 1
-        fL = glob.glob( 'TestResults.*/auto2/auto2.xml' )
-        assert len(fL) == 1
+        util.runvvtest().assertCounts( total=2, npass=2 )
+
+        assert len( glob.glob( 'TestResults.*/auto1/auto1.xml' ) ) == 1
+        assert len( glob.glob( 'TestResults.*/auto2/auto2.xml' ) ) == 1
 
     def test_filtering_execute_blocks_by_test_name(self):
         ""
@@ -350,17 +330,18 @@ class execute_tests( unittest.TestCase ):
                 <execute testname="multi2"> echo "multi2 only" </execute>
                 <execute testname="multi or multi2"> echo "both tests" </execute>
             </rtest>""" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 2 and nd == 0 and nf == 0 and nn == 0
-        fL = glob.glob( 'TestResults.*/multi/execute.log' )
-        assert len(fL) == 1
-        assert len( util.filegrep( fL[0], 'multi only' ) ) >= 1
-        assert len( util.filegrep( fL[0], 'both tests' ) ) >= 1
-        fL = glob.glob( 'TestResults.*/multi2/execute.log' )
-        assert len(fL) == 1
-        assert len( util.filegrep( fL[0], 'multi2 only' ) ) >= 1
-        assert len( util.filegrep( fL[0], 'both tests' ) ) >= 1
+        vrun = util.runvvtest()
+        vrun.assertCounts( total=2, npass=2 )
+
+        xpat = 'TestResults.*/multi/execute.log'
+        assert len( util.grepfiles( 'multi only', xpat ) ) == 1
+        assert len( util.grepfiles( 'both tests', xpat ) ) == 1
+
+        xpat = 'TestResults.*/multi2/execute.log'
+        assert len( util.grepfiles( 'multi2 only', xpat ) ) == 1
+        assert len( util.grepfiles( 'both tests', xpat ) ) == 1
 
     def test_using_NOT_in_the_test_name_filter(self):
         ""
@@ -371,17 +352,18 @@ class execute_tests( unittest.TestCase ):
                 <execute testname="not multi"> echo "multi2 only" </execute>
                 <execute testname="multi or multi2"> echo "both tests" </execute>
             </rtest>""" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 2 and nd == 0 and nf == 0 and nn == 0
-        fL = glob.glob( 'TestResults.*/multi/execute.log' )
-        assert len(fL) == 1
-        assert len( util.filegrep( fL[0], 'multi only' ) ) >= 1
-        assert len( util.filegrep( fL[0], 'both tests' ) ) >= 1
-        fL = glob.glob( 'TestResults.*/multi2/execute.log' )
-        assert len(fL) == 1
-        assert len( util.filegrep( fL[0], 'multi2 only' ) ) >= 1
-        assert len( util.filegrep( fL[0], 'both tests' ) ) >= 1
+        vrun = util.runvvtest()
+        vrun.assertCounts( total=2, npass=2 )
+
+        xpat = 'TestResults.*/multi/execute.log'
+        assert len( util.grepfiles( 'multi only', xpat ) ) == 1
+        assert len( util.grepfiles( 'both tests', xpat ) ) == 1
+
+        xpat = 'TestResults.*/multi2/execute.log'
+        assert len( util.grepfiles( 'multi2 only', xpat ) ) == 1
+        assert len( util.grepfiles( 'both tests', xpat ) ) == 1
 
     def test_behavior_when_two_tests_have_the_same_filename_path(self):
         ""
@@ -394,32 +376,33 @@ class execute_tests( unittest.TestCase ):
             <rtest name="dup">
                 <execute> echo "test bdir" </execute>
             </rtest>""" )
+        time.sleep(1)
 
         # the bdir test should be selected because it is scanned first
-        out,np,nd,nf,nn = util.run_vvtest( 'bdir adir' )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tdir = util.results_dir()
-        xf = os.path.join( tdir, 'subdir', 'dup', 'execute.log' )
-        assert len( util.filegrep( xf, 'test bdir' ) ) == 1
-        assert len( util.filegrep( xf, 'test adir' ) ) == 0
+        vrun = util.runvvtest( 'bdir adir' )
+        vrun.assertCounts( total=1, npass=1 )
 
-        fl = os.readlink( os.path.join( tdir, 'subdir', 'dup', 'dup.xml' ) )
-        s = 'bdir/subdir/dup.xml'
-        assert fl[-len(s):] == s
+        assert vrun.countGrepLogs( 'test bdir' ) == 1
+        assert vrun.countGrepLogs( 'test adir' ) == 0
+
+        fL = util.findfiles( 'dup.xml', 'TestResults.*' )
+        assert len( fL ) == 1
+        fn = os.readlink( fL[0] )
+        assert os.path.samefile( fn, 'bdir/subdir/dup.xml' )
 
         util.remove_results()
 
         # now the adir test should be selected
-        out,np,nd,nf,nn = util.run_vvtest( 'adir bdir' )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tdir = util.results_dir()
-        xf = os.path.join( tdir, 'subdir', 'dup', 'execute.log' )
-        assert len( util.filegrep( xf, 'test adir' ) ) == 1
-        assert len( util.filegrep( xf, 'test bdir' ) ) == 0
+        vrun = util.runvvtest( 'adir bdir' )
+        vrun.assertCounts( total=1, npass=1 )
 
-        fl = os.readlink( os.path.join( tdir, 'subdir', 'dup', 'dup.xml' ) )
-        s = 'adir/subdir/dup.xml'
-        assert fl[-len(s):] == s
+        assert vrun.countGrepLogs( 'test bdir' ) == 0
+        assert vrun.countGrepLogs( 'test adir' ) == 1
+
+        fL = util.findfiles( 'dup.xml', 'TestResults.*' )
+        assert len( fL ) == 1
+        fn = os.readlink( fL[0] )
+        assert os.path.samefile( fn, 'adir/subdir/dup.xml' )
 
 
 ############################################################################
diff --git a/vvt/libvvtest/tests/info b/vvt/libvvtest/tests/info
--- a/vvt/libvvtest/tests/info
+++ b/vvt/libvvtest/tests/info
@@ -27,61 +27,50 @@ class info_tests( unittest.TestCase ):
         util.writefile( "param.xml", """
             <rtest name="param">
               <parameterize hello="world mars"/>
-              <execute> <![CDATA[
-            sleep 1
-            echo "parm=$hello"
-            ]]>
+              <execute>
+                sleep 1
+                echo "parm=$hello"
               </execute>
             </rtest>""" )
-
         util.writefile( "FailTest.xml", """
             <rtest name="FailTest">
-              <execute> <![CDATA[
-            sleep 1
-            echo "Exiting with failure status"
-            exit 1
-            ]]>
+              <execute>
+                sleep 1
+                echo "Exiting with failure status"
+                exit 1
               </execute>
             </rtest>""")
-
         util.writefile( "DiffTest.xml", """
             <rtest name="DiffTest">
-              <execute> <![CDATA[
-            sleep 1
-            echo "Exiting with diff status"
-            set have_diff = yes
-            ]]>
+              <execute>
+                sleep 1
+                echo "Exiting with diff status"
+                set have_diff = yes
               </execute>
             </rtest>""")
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 2 and nd == 1 and nf == 1 and nn == 0
-        assert len( util.testlist(out) ) == 4, "expected 4 tests to have run"
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np == 2 and nd == 1 and nf == 1 and nn == 0
-        assert len( util.testlist(out) ) == 4, "expected 4 tests to have run"
+        vrun = util.runvvtest()
+        vrun.assertCounts( total=4, npass=2, diff=1, fail=1 )
+        tdir = vrun.resultsDir()
+
+        vrun = util.runvvtest( '-i' )
+        vrun.assertCounts( total=4, npass=2, diff=1, fail=1 )
 
         # cd into the run directory and check the -i output
-        saved = os.getcwd()
-        os.chdir( util.results_dir() )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np == 2 and nd == 1 and nf == 1 and nn == 0
-        assert len( util.testlist(out) ) == 4, "expected 4 tests to have run"
-        os.chdir(saved)
+        vrun = util.runvvtest( '-i', chdir=tdir )
+        vrun.assertCounts( total=4, npass=2, diff=1, fail=1 )
 
         util.remove_results()
 
         # again but with a build option
 
-        out,np,nd,nf,nn = util.run_vvtest( '-o dbg' )
-        assert np == 2 and nd == 1 and nf == 1 and nn == 0
-        assert len( util.testlist(out) ) == 4, "expected 4 tests to have run"
+        vrun = util.runvvtest( '-o dbg' )
+        vrun.assertCounts( total=4, npass=2, diff=1, fail=1 )
+        tdir = vrun.resultsDir()
 
-        os.chdir( util.results_dir() )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np == 2 and nd == 1 and nf == 1 and nn == 0
-        assert len( util.testlist(out) ) == 4, "expected 4 tests to have run"
-        os.chdir(saved)
+        vrun = util.runvvtest( '-i', chdir=tdir )
+        vrun.assertCounts( total=4, npass=2, diff=1, fail=1 )
 
         util.remove_results()
 
@@ -90,90 +79,60 @@ class info_tests( unittest.TestCase ):
                 <keywords> hello world </keywords>
               </rtest>
             """ )
-
         util.writefile( 'sdir/skeys.xml', """
               <rtest name="skeys">
                 <keywords> mars jupiter fast </keywords>
               </rtest>
             """ )
+        time.sleep(1)
 
-        rootd = os.getcwd()
+        vrun = util.runvvtest( '--keys' )
+        assert_keywords( vrun, ['fast', 'hello', 'jupiter', 'mars', 'world'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--keys' )
-        L = extract_keywords(out)
-        print3( "keywords", L )
-        assert L == ['fast', 'hello', 'jupiter', 'mars', 'world']
+        vrun = util.runvvtest( '--files' )
+        assert_files( vrun, [ 'DiffTest.xml', 'FailTest.xml', 'keys.xml',
+                              'param.xml', 'sdir/skeys.xml' ] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--files' )
-        L = extract_files(out, rootd)
-        print3( "files", L )
-        assert L == [ 'DiffTest.xml', 'FailTest.xml', 'keys.xml', \
-                      'param.xml', 'sdir/skeys.xml']
+        vrun = util.runvvtest( '-k fast --files' )
+        assert_files( vrun, [ 'sdir/skeys.xml'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-k fast --files' )
-        L = extract_files(out, rootd)
-        print3( "files", L )
-        assert L == [ 'sdir/skeys.xml']
+        vrun = util.runvvtest( '-K fast -K medium -K long --files' )
+        assert_files( vrun, [ 'DiffTest.xml', 'FailTest.xml',
+                              'keys.xml', 'param.xml'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-K fast -K medium -K long --files' )
-        L = extract_files(out, rootd)
-        print3( "files", L )
-        assert L == [ 'DiffTest.xml', 'FailTest.xml', 'keys.xml', 'param.xml']
+        vrun = util.runvvtest()
+        tdir = vrun.resultsDir()
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        out,np,nd,nf,nn = util.run_vvtest( '-R --keys' )
-        L = extract_keywords(out)
-        print3( "keywords", L )
-        assert L == ['fast', 'hello', 'jupiter', 'mars', 'world']
+        vrun = util.runvvtest( '-R --keys' )
+        assert_keywords( vrun, ['fast', 'hello', 'jupiter', 'mars', 'world'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --keys' )
-        L = extract_keywords(out)
-        print3( "keywords", L )
-        assert L == ['fast', 'hello', 'jupiter', 'mars', 'world']
+        vrun = util.runvvtest( '-i --keys' )
+        assert_keywords( vrun, ['fast', 'hello', 'jupiter', 'mars', 'world'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --files' )
-        L = extract_files(out, rootd)
-        print3( "files", L )
-        assert L == [ 'DiffTest.xml', 'FailTest.xml', 'keys.xml', \
-                      'param.xml', 'sdir/skeys.xml']
+        vrun = util.runvvtest( '-i --files' )
+        assert_files( vrun, [ 'DiffTest.xml', 'FailTest.xml', 'keys.xml',
+                              'param.xml', 'sdir/skeys.xml'] )
 
-        os.chdir( util.results_dir() )
+        vrun = util.runvvtest( '-R --keys', chdir=tdir )
+        assert_keywords( vrun, ['fast', 'hello', 'jupiter', 'mars', 'world'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-R --keys' )
-        L = extract_keywords(out)
-        print3( "keywords", L )
-        assert L == ['fast', 'hello', 'jupiter', 'mars', 'world']
+        vrun = util.runvvtest( '-i --keys', chdir=tdir )
+        assert_keywords( vrun, ['fast', 'hello', 'jupiter', 'mars', 'world'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --keys' )
-        L = extract_keywords(out)
-        print3( "keywords", L )
-        assert L == ['fast', 'hello', 'jupiter', 'mars', 'world']
+        vrun = util.runvvtest( '-i --files', chdir=tdir )
+        assert_files( vrun, [ 'DiffTest.xml', 'FailTest.xml', 'keys.xml',
+                              'param.xml', 'sdir/skeys.xml'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --files' )
-        L = extract_files(out, rootd)
-        print3( "files", L )
-        assert L == [ 'DiffTest.xml', 'FailTest.xml', 'keys.xml', \
-                      'param.xml', 'sdir/skeys.xml']
+        util.runvvtest( '-i', chdir=tdir+'/sdir' ).assertCounts( total=1 )
 
-        os.chdir( 'sdir' )
+        vrun = util.runvvtest( '-R --keys', chdir=tdir+'/sdir' )
+        assert_keywords( vrun, ['fast', 'jupiter', 'mars'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np+nd+nf == 1
+        vrun = util.runvvtest( '-i --keys', chdir=tdir+'/sdir' )
+        assert_keywords( vrun, ['fast', 'jupiter', 'mars'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '-R --keys' )
-        L = extract_keywords(out)
-        print3( "keywords", L )
-        assert L == ['fast', 'jupiter', 'mars']
-
-        out,np,nd,nf,nn = util.run_vvtest( '-i --keys' )
-        L = extract_keywords(out)
-        print3( "keywords", L )
-        assert L == ['fast', 'jupiter', 'mars']
-
-        out,np,nd,nf,nn = util.run_vvtest( '-i --files' )
-        L = extract_files(out, rootd)
-        print3( "files", L )
-        assert L == ['sdir/skeys.xml']
+        vrun = util.runvvtest( '-i --files', chdir=tdir+'/sdir' )
+        assert_files( vrun, [ 'sdir/skeys.xml'] )
 
     def test_sorting_the_test_listing(self):
         ""
@@ -203,42 +162,36 @@ class info_tests( unittest.TestCase ):
                 sleep 20
               </execute>
             </rtest>""" )
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest( '-T 10 -n 1' )
-        assert np == 1 and nd == 1 and nf == 1 and nn == 0
-        tdir = os.path.abspath( util.results_dir() )
+        vrun = util.runvvtest( '-T 10 -n 1' )
+        vrun.assertCounts( total=4, npass=1, diff=1, fail=1, timeout=1 )
 
-        L = util.greptestlist( out, 'TestResults' )
-        assert len(L) == 4
-        assert [ s.split()[0] for s in L ] == ['ardvark','marmot','otter','zebra']
+        finL = vrun.grep( 'Finished: ' )
+        assert len(finL) == 4
+        xorder = [ line.split()[1] for line in finL ]
+        for nam in ['ardvark','marmot','otter','zebra']:
+            assert nam in xorder
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i', directory=tdir )
-        L = util.testlines( out )
-        assert [ s.split()[0] for s in L ] == ['ardvark','marmot','otter','zebra']
+        tdir = vrun.resultsDir()
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --sort nx', directory=tdir )
-        L = util.testlines( out )
-        assert [ s.split()[0] for s in L ] == ['ardvark','marmot','otter','zebra']
+        vrun = util.runvvtest( '-i', chdir=tdir )
+        assert test_names( vrun ) == ['ardvark','marmot','otter','zebra']
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --sort x', directory=tdir )
-        L = util.testlines( out )
-        assert [ s.split()[0] for s in L ] == ['marmot','zebra','ardvark','otter']
+        vrun = util.runvvtest( '-i --sort nx', chdir=tdir )
+        assert test_names( vrun ) == ['ardvark','marmot','otter','zebra']
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --sort t', directory=tdir )
-        L = util.testlines( out )
-        assert [ s.split()[0] for s in L ] == ['zebra','marmot','ardvark','otter']
+        vrun = util.runvvtest( '-i --sort x', chdir=tdir )
+        assert test_names( vrun ) == ['marmot','zebra','ardvark','otter']
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --sort sr', directory=tdir )
-        L = util.testlines( out )
-        assert [ s.split()[0] for s in L ] == ['otter','ardvark','zebra','marmot']
+        vrun = util.runvvtest( '-i --sort t', chdir=tdir )
+        assert test_names( vrun ) == ['zebra','marmot','ardvark','otter']
 
-        out,np,nd,nf,nn = util.run_vvtest( '-i --sort d', directory=tdir )
-        L = util.testlines( out )
-        # just make sure the dates are sorted in ascending order
-        L2 = [ line.split()[4]+' '+line.split()[5] for line in L ]
-        L3 = [] + L2
-        L3.sort()
-        assert L2 == L3
+        vrun = util.runvvtest( '-i --sort sr', chdir=tdir )
+        assert test_names( vrun ) == ['otter','ardvark','zebra','marmot']
+
+        vrun = util.runvvtest( '-i --sort d', chdir=tdir )
+        assert test_names( vrun ) == xorder
 
     def test_using_the_files_option_with_a_multi_test_xml_file(self):
         ""
@@ -249,28 +202,19 @@ class info_tests( unittest.TestCase ):
               <keywords testname="horse"> patchwork </keywords>
               <execute> echo "hello world" </execute>
             </rtest>""" )
+        time.sleep(1)
 
-        cwd = os.getcwd()
+        vrun = util.runvvtest( '--files' )
+        assert_files( vrun, [ 'multi.xml'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--files' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 1
+        vrun = util.runvvtest( '--files -k stripes' )
+        assert_files( vrun, [ 'multi.xml'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--files -k stripes' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 1
+        vrun = util.runvvtest( '--files -k patchwork' )
+        assert_files( vrun, [ 'multi.xml'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--files -k patchwork' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 1
-
-        out,np,nd,nf,nn = util.run_vvtest( '--files -k stripes -k patchwork' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 0
+        vrun = util.runvvtest( '--files -k stripes -k patchwork' )
+        assert_files( vrun, [] )
 
     def test_using_the_files_option_with_a_multi_test_script_file(self):
         ""
@@ -282,45 +226,23 @@ class info_tests( unittest.TestCase ):
             #VVT: keywords (testname=horse) : patchwork
             echo "hello world"
             """ )
+        time.sleep(1)
 
-        cwd = os.getcwd()
+        vrun = util.runvvtest( '--files' )
+        assert_files( vrun, [ 'multi.vvt'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--files' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 1
+        vrun = util.runvvtest( '--files -k stripes' )
+        assert_files( vrun, [ 'multi.vvt'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--files -k stripes' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 1
+        vrun = util.runvvtest( '--files -k patchwork' )
+        assert_files( vrun, [ 'multi.vvt'] )
 
-        out,np,nd,nf,nn = util.run_vvtest( '--files -k patchwork' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 1
-
-        out,np,nd,nf,nn = util.run_vvtest( '--files -k stripes -k patchwork' )
-        L = extract_files( out, cwd )
-        print3( "files", L )
-        assert len(L) == 0
+        vrun = util.runvvtest( '--files -k stripes -k patchwork' )
+        assert_files( vrun, [] )
 
     def test_using_files_option_should_apply_max_processors_filtering(self):
         ""
-        util.writescript( "null.vvt", """
-            #!/bin/sh
-            echo "null"
-            """ )
-        out,np,nd,nf,nn = util.run_vvtest()
-        platname = util.platform_name( out )
-        tdir = util.results_dir()
-        os.remove( 'null.vvt' )
-        L = util.grep( out, 'max procs' )
-        assert len(L) == 1
-        maxprocs = L[0].split( 'max procs', 1 )[1].strip().lstrip('=').strip()
-        maxprocs = int( maxprocs )
-        assert maxprocs > 0
-        util.remove_results()
+        maxprocs = 4
 
         util.writescript( 'atest.vvt', """
             #!/usr/bin/env python
@@ -347,61 +269,70 @@ class info_tests( unittest.TestCase ):
             print ( 'executing test, np='+str(vvt.np) )
             """ )
 
-        rootd = os.getcwd()
-
-        out,np,nd,nf,nn = util.run_vvtest( '--files' )
-        L = extract_files( out, rootd )
-        print3( "files", L )
-        assert L == [ 'atest.vvt', 'btest.vvt']
+        vrun = util.runvvtest( '-N '+str(maxprocs)+' --files' )
+        assert_files( vrun, [ 'atest.vvt', 'btest.vvt' ] )
 
     def test_producing_a_JUnit_results_file(self):
         ""
         util.writefile( "subdir/param.xml", """
             <rtest name="param">
               <parameterize hello="world mars"/>
-              <execute> <![CDATA[
-            sleep 1
-            echo "parm=$hello"
-            ]]>
+              <execute>
+                sleep 1
+                echo "parm=$hello"
               </execute>
             </rtest>""" )
-
         util.writefile( "FailTest.xml", """
             <rtest name="FailTest">
-              <execute> <![CDATA[
-            sleep 1
-            echo "Exiting with failure status"
-            exit 1
-            ]]>
+              <execute>
+                sleep 1
+                echo "Exiting with failure status"
+                exit 1
               </execute>
             </rtest>""")
-
         util.writefile( "DiffTest.xml", """
             <rtest name="DiffTest">
               <parameterize np="1 2"/>
-              <execute> <![CDATA[
-            sleep 1
-            echo "Exiting with diff status"
-            set have_diff = yes
-            ]]>
+              <execute>
+                sleep 1
+                echo "Exiting with diff status"
+                set have_diff = yes
               </execute>
             </rtest>""")
+        time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest()
-        assert np == 2 and nd == 2 and nf == 1 and nn == 0
-        assert len( util.testlist(out) ) == 5, "expected 5 tests to have run"
+        vrun = util.runvvtest()
+        vrun.assertCounts( total=5, npass=2, diff=2, fail=1 )
 
-        # cd into the run directory and produce the JUnit XML file
-        saved = os.getcwd()
-        os.chdir( util.results_dir() )
-        util.run_vvtest( '-i --junit=../ju.xml' )
-        os.chdir(saved)
-        assert len( util.filegrep( 'ju.xml', '<testcase ' ) ) == 5
+        vrun = util.runvvtest( '-i --junit=../ju.xml', chdir=vrun.resultsDir() )
+
+        assert len( util.grepfiles( '<testcase ', 'ju.xml' ) ) == 5
 
 
 ############################################################################
 
+def assert_keywords( vrun, keywordlist ):
+    ""
+    kL = extract_keywords( vrun.out )
+    assert kL == keywordlist
+
+
+def assert_files( vrun, relative_filenames ):
+    ""
+    fL = extract_files( vrun.out, os.getcwd() )
+    assert fL == relative_filenames
+
+
+def test_names( vrun ):
+    ""
+    nameL = []
+    for line in util.testlines( vrun.out ):
+        nameL.append( line.split()[0] )
+    return nameL
+
+
 def extract_keywords( out ):
+    ""
     start = False
     kL = []
     for line in out.split( '\n' ):
@@ -416,7 +347,9 @@ def extract_keywords( out ):
     L.sort()
     return L
 
+
 def extract_files( out, rootd ):
+    ""
     D = {}
     for line in out.split( '\n' ):
       line = line.strip()
diff --git a/vvt/libvvtest/tests/restart b/vvt/libvvtest/tests/restart
--- a/vvt/libvvtest/tests/restart
+++ b/vvt/libvvtest/tests/restart
@@ -11,6 +11,7 @@ sys.dont_write_bytecode = True
 sys.excepthook = sys.__excepthook__
 import os
 import time
+import glob
 import unittest
 
 import testutils as util
@@ -27,61 +28,51 @@ class restart_tests( unittest.TestCase ):
         util.writefile( "param.xml", """
             <rtest name="param">
               <parameterize hello="world mars"/>
-              <execute> <![CDATA[
+              <execute>
                 sleep 1
-                echo "parm=$hello"
-              ]]>
               </execute>
             </rtest>""" )
-
         util.writefile( "FailTest.xml", """
             <rtest name="FailTest">
-              <execute> <![CDATA[
+              <execute>
                 sleep 1
-                echo "Exiting with failure status"
                 exit 1
-              ]]>
               </execute>
             </rtest>""")
-
         util.writefile( "DiffTest.xml", """
             <rtest name="DiffTest">
-              <execute> <![CDATA[
+              <execute>
                 sleep 1
-                echo "Exiting with diff status"
                 set have_diff = yes
-              ]]>
               </execute>
             </rtest>""")
+        time.sleep(1)
 
         # run the test set but provide a false interruption
         util.interrupt_vvtest_run( '-n 2', count=1 )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np+nd+nf+nn == 4
-        assert np < 2 or nd < 1 or nf < 1
+        vrun = util.runvvtest( '-i' )
+        cntD = util.parse_vvtest_counts( vrun.out )
+        assert cntD['total'] == 4 and cntD['notrun'] > 0
 
         # restart with no keywords
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2' )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np == 2 and nd == 1 and nf == 1 and nn == 0
+        util.runvvtest( '-n 2' )
+        util.runvvtest( '-i' ).assertCounts( total=4, npass=2, diff=1, fail=1 )
 
         # restart using results keyword
         util.interrupt_vvtest_run( '-n 2 -w', count=1 )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np+nd+nf+nn == 4
-        assert np < 2 or nd < 1 or nf < 1
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2 -k notrun/notdone' )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np+nd+nf+nn == 4
+        vrun = util.runvvtest( '-i' )
+        cntD = util.parse_vvtest_counts( vrun.out )
+        assert cntD['total'] == 4 and cntD['notrun'] > 0
+
+        util.runvvtest( '-n 2 -k notrun/notdone' )
+        util.runvvtest( '-i' ).assertCounts( total=4, npass=2, diff=1, fail=1 )
 
         # none should restart now
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2' )
-        assert np+nd+nf+nn == 0
+        util.runvvtest( '-n 2' ).assertCounts( total=0 )
 
-        # all of them should run again (the -F has been replaced by -R but use it
-        # here to test it still works, can be removed in the future [May 2016])
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2 -F' )
-        assert np+nd+nf+nn == 4
+        # all of them should run again
+        vrun = util.runvvtest( '-n 2 -R' )
+        vrun.assertCounts( total=4, npass=2, diff=1, fail=1 )
 
     def test_prerun_file_cleanout(self):
         ""
@@ -96,77 +87,70 @@ class restart_tests( unittest.TestCase ):
               ]]>
               </execute>
             </rtest>""" )
+        time.sleep(1)
 
-        self.prerun_file_cleanout( '' )
-        self.prerun_file_cleanout(
-            '--plat '+util.core_platform_name()+' --batch' )
+        for batch in [False,True]:
 
-    def prerun_file_cleanout(self, opt):
-        ""
-        util.remove_results()
+            util.remove_results()
 
-        out,np,nd,nf,nn = util.run_vvtest( opt )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tdir = os.path.abspath( util.results_dir() )
-        assert os.path.exists( tdir+'/clean/generated_file.txt' )
+            vrun = util.runvvtest( batch=batch )
+            vrun.assertCounts( total=1, npass=1 )
 
-        # run again should remove the generated file
-        out,np,nd,nf,nn = util.run_vvtest( opt+' -R' )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        assert len( util.filegrep( tdir+'/clean/execute.log', 'existing.*generated' ) ) == 0
+            assert len( glob.glob( 'TestResults*/clean/generated_file.txt' ) ) == 1
 
-        # running again with -m option should fail
-        out,np,nd,nf,nn = util.run_vvtest( opt+' -R -m' )
-        assert np == 0 and nd == 0 and nf == 1 and nn == 0
-        assert len( util.filegrep( tdir+'/clean/execute.log', 'existing.*generated' ) ) == 1
+            # the generated file should be removed prior to running the script
+            vrun = util.runvvtest( '-R', batch=batch )
+            vrun.assertCounts( total=1, npass=1 )
+            assert vrun.countGrepLogs( 'existing*generated' ) == 0
+
+            # with -m option should fail because of "noclobber" in script
+            vrun = util.runvvtest( '-R -m', batch=batch )
+            vrun.assertCounts( total=1, fail=1 )
+            assert vrun.countGrepLogs( 'existing*generated' ) == 1
 
     def test_run_then_fix_a_test_then_restart(self):
         ""
-        self.run_then_fix_a_test_then_restart( '' )
-        self.run_then_fix_a_test_then_restart(
-            '--plat '+util.core_platform_name()+' --batch' )
+        for batch in [False,True]:
 
-    def run_then_fix_a_test_then_restart(self, opt):
-        ""
-        util.writefile( 'atest.xml', """
-            <rtest name="atest">
-              <parameterize timestep="1 2"/>
-              <execute>
-                if ( "$timestep" == 2 ) then
-                  echo "fake failure"
-                  exit 1
-                else
-                  touch atest.$timestep
-                endif
-              </execute>
-              <analyze>
-                 ls ../atest.timestep=1/atest.1 || exit 1
-                 ls ../atest.timestep=2/atest.2 || exit 1
-              </analyze>
-            </rtest>""" )
+            util.writefile( 'atest.xml', """
+                <rtest name="atest">
+                  <parameterize timestep="1 2"/>
+                  <execute>
+                    if ( "$timestep" == 2 ) then
+                      echo "fake failure"
+                      exit 1
+                    else
+                      touch atest.$timestep
+                    endif
+                  </execute>
+                  <analyze>
+                     ls ../atest.timestep=1/atest.1 || exit 1
+                     ls ../atest.timestep=2/atest.2 || exit 1
+                  </analyze>
+                </rtest>""" )
+            time.sleep(1)
 
-        util.remove_results()
+            util.remove_results()
 
-        out,np,nd,nf,nn = util.run_vvtest( opt )
-        assert np == 1 and nd == 0 and nf == 1 and nn == 1
-        tdir = os.path.abspath( util.results_dir() )
-        platname = util.platform_name( out )
+            vrun = util.runvvtest( batch=batch )
+            vrun.assertCounts( total=3, npass=1, fail=1, notrun=1 )
 
-        # "fix" the test and restart
-        util.writefile( 'atest.xml', """
-            <rtest name="atest">
-              <parameterize timestep="1 2"/>
-              <execute>
-                touch atest.$timestep
-              </execute>
-              <analyze>
-                 ls ../atest.timestep=1/atest.1 || exit 1
-                 ls ../atest.timestep=2/atest.2 || exit 1
-              </analyze>
-            </rtest>""" )
+            # "fix" the test and restart
+            util.writefile( 'atest.xml', """
+                <rtest name="atest">
+                  <parameterize timestep="1 2"/>
+                  <execute>
+                    touch atest.$timestep
+                  </execute>
+                  <analyze>
+                     ls ../atest.timestep=1/atest.1 || exit 1
+                     ls ../atest.timestep=2/atest.2 || exit 1
+                  </analyze>
+                </rtest>""" )
+            time.sleep(1)
 
-        out,np,nd,nf,nn = util.run_vvtest( opt+' -k fail/notrun' )
-        assert np == 2 and nd == 0 and nf == 0 and nn == 0
+            vrun = util.runvvtest( '-k fail/notrun', batch=batch )
+            vrun.assertCounts( total=2, npass=2 )
 
     def test_restarting_script_tests(self):
         ""
@@ -190,32 +174,33 @@ class restart_tests( unittest.TestCase ):
             vvt.set_have_diff()
             vvt.if_diff_exit_diff()
             """[1:] )
+        time.sleep(1)
 
         # run the test set but provide a false interruption
         util.interrupt_vvtest_run( '-n 2', count=1 )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np < 2 or nd < 1 or nf < 1
+        vrun = util.runvvtest( '-i' )
+        cntD = util.parse_vvtest_counts( vrun.out )
+        assert cntD['total'] == 4 and cntD['notrun'] > 0
 
         # restart with no keywords
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2' )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np == 2 and nd == 1 and nf == 1 and nn == 0
+        util.runvvtest( '-n 2' )
+        util.runvvtest( '-i' ).assertCounts( total=4, npass=2, diff=1, fail=1 )
 
         # restart using results keyword
         util.interrupt_vvtest_run( '-n 2 -w', count=1 )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np < 2 or nd < 1 or nf < 1
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2 -k notrun/notdone' )
-        out,np,nd,nf,nn = util.run_vvtest( '-i' )
-        assert np+nd+nf+nn == 4
+        vrun = util.runvvtest( '-i' )
+        cntD = util.parse_vvtest_counts( vrun.out )
+        assert cntD['total'] == 4 and cntD['notrun'] > 0
+
+        util.runvvtest( '-n 2 -k notrun/notdone' )
+        util.runvvtest( '-i' ).assertCounts( total=4, npass=2, diff=1, fail=1 )
 
         # none should restart now
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2' )
-        assert np+nd+nf+nn == 0
+        util.runvvtest( '-n 2' ).assertCounts( total=0 )
 
         # all of them should run again
-        out,np,nd,nf,nn = util.run_vvtest( '-n 2 -R' )
-        assert np+nd+nf+nn == 4
+        vrun = util.runvvtest( '-n 2 -R' )
+        vrun.assertCounts( total=4, npass=2, diff=1, fail=1 )
 
     def test_prerun_file_cleanout_with_a_script_test(self):
         ""
@@ -229,30 +214,26 @@ class restart_tests( unittest.TestCase ):
             fp.write( 'gen file contents' )
             fp.close()
             """ )
+        time.sleep(1)
 
-        self.prerun_file_cleanout_with_a_script_test( '' )
-        self.prerun_file_cleanout_with_a_script_test(
-            '--plat '+util.core_platform_name()+' --batch' )
+        for batch in [False,True]:
 
-    def prerun_file_cleanout_with_a_script_test(self, opt):
-        ""
-        util.remove_results()
+            util.remove_results()
 
-        out,np,nd,nf,nn = util.run_vvtest( opt )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tdir = os.path.abspath( util.results_dir() )
-        platname = util.platform_name( out )
-        assert os.path.exists( tdir+'/clean/generated_file.txt' )
+            vrun = util.runvvtest( batch=batch )
+            vrun.assertCounts( total=1, npass=1 )
 
-        # run again should remove the generated file
-        out,np,nd,nf,nn = util.run_vvtest( opt+' -R' )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        assert len( util.filegrep( tdir+'/clean/execute.log', 'existing.*generated' ) ) == 0
+            assert len( glob.glob( 'TestResults*/clean/generated_file.txt' ) ) == 1
 
-        # running again with -m option should fail
-        out,np,nd,nf,nn = util.run_vvtest( opt+' -R -m' )
-        assert np == 0 and nd == 0 and nf == 1 and nn == 0
-        assert len( util.filegrep( tdir+'/clean/execute.log', 'existing.*generated' ) ) == 1
+            # the generated file should be removed prior to running the script
+            vrun = util.runvvtest( '-R', batch=batch )
+            vrun.assertCounts( total=1, npass=1 )
+            assert vrun.countGrepLogs( 'existing*generated' ) == 0
+
+            # with -m option should fail because of "noclobber" in script
+            vrun = util.runvvtest( '-R -m', batch=batch )
+            vrun.assertCounts( total=1, fail=1 )
+            assert vrun.countGrepLogs( 'existing*generated' ) == 1
 
     def test_prerun_file_cleanout_when_test_contains_a_soft_linked_directory(self):
         ""
@@ -266,29 +247,28 @@ class restart_tests( unittest.TestCase ):
         util.writefile( 'subdir/afile.txt', """
             contents of file
             """ )
+        time.sleep(1)
 
-        self.prerun_file_cleanout_when_test_contains_a_soft_linked_directory( '' )
-        self.prerun_file_cleanout_when_test_contains_a_soft_linked_directory(
-            '--plat '+util.core_platform_name()+' --batch' )
+        for batch in [False,True]:
 
-    def prerun_file_cleanout_when_test_contains_a_soft_linked_directory(self, opt):
-        ""
-        util.remove_results()
+            util.remove_results()
 
-        out,np,nd,nf,nn = util.run_vvtest( opt )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        tdir = os.path.abspath( util.results_dir() )
-        assert os.path.exists( tdir+'/softdir/subdir/afile.txt' )
+            vrun = util.runvvtest( batch=batch )
+            vrun.assertCounts( total=1, npass=1 )
 
-        # run again exercises the pre-clean logic
-        out,np,nd,nf,nn = util.run_vvtest( opt+' -R' )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        assert os.path.exists( tdir+'/softdir/subdir/afile.txt' )
+            fL = glob.glob( 'TestResults*/softdir/subdir/afile.txt' )
+            assert len(fL) == 1
+            afile = fL[0]
 
-        # now with post-clean (soft links are not cleaned)
-        out,np,nd,nf,nn = util.run_vvtest( opt+' -R -C' )
-        assert np == 1 and nd == 0 and nf == 0 and nn == 0
-        assert os.path.exists( tdir+'/softdir/subdir/afile.txt' )
+            # run again exercises the pre-clean logic
+            vrun = util.runvvtest( '-R', batch=batch )
+            vrun.assertCounts( total=1, npass=1 )
+            assert os.path.exists( afile )
+
+            # now with post-clean (soft links are not cleaned)
+            vrun = util.runvvtest( '-R -C', batch=batch )
+            vrun.assertCounts( total=1, npass=1 )
+            assert os.path.exists( afile )
 
 
 ########################################################################
